In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

import matplotlib.pyplot as plt
url='/content/drive/MyDrive/ColabData/'
df = pd.read_csv(url+'recommendation_dataset.csv')
df

   user_id  watch_time   genre  recommended
0        1         120  Action            1
1        2          45   Drama            0
2        3         300  Action            1
3        4         150  Comedy            1
4        5          80   Drama            0

In [6]:
le = LabelEncoder()
df['genre'] =le.fit_transform(df['genre'])
df

   user_id  watch_time  genre  recommended
0        1         120      0            1
1        2          45      2            0
2        3         300      0            1
3        4         150      1            1
4        5          80      2            0

In [7]:
X = df[['watch_time', 'genre']]
Y = df['recommended']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.4)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

   watch_time  genre
3         150      1
1          45      2
2         300      0
   watch_time  genre
0         120      0
4          80      2
3    1
1    0
2    1
Name: recommended, dtype: int64
0    1
4    0
Name: recommended, dtype: int64

In [15]:
model = DecisionTreeClassifier()
model.fit(X_train, y_train)
print('accuracy ', model.score(X_test, y_test))

accuracy  1.0

In [21]:
input_data = pd.DataFrame({
    "watch_time" : [10],
    "genre": [le.transform(["Action"])[0]]
})
model.predict(input_data)

array([0])

metric - measured(age, salary, price)
nominal - male, female(Categorical) , sentiments, place, company
ordinal - ordered: education, rating